const INFORMATIONAL: [i16; 4] = [100, 101, 102, 103];
const SUCCESS: [i16; 10] = [200, 201, 202, 203, 204, 205, 206, 207, 208, 226];
const REDIRECTION: [i16; 9] = [300, 301, 302, 303, 304, 305, 306, 307, 308];
const CLIENT_ERROR: [i16; 28] = [
    400, 401, 402, 403, 404, 405, 406, 407, 408, 409, 410, 411, 412, 413, 414, 415, 416, 417, 418,
    421, 422, 423, 424, 426, 428, 429, 431, 451,
];
const SERVER_ERROR: [i16; 11] = [500, 501, 502, 503, 504, 505, 506, 507, 508, 510, 511];

enum HttpsStatusType {
    INFORMATIONAL,
    SUCCESSFUL,
    REDIRECTION,
    CLIENT_ERROR,
    SERVER_ERROR,
}
struct HttpStatus {
    code: i16,
    title: &'static str,
    explanation: &'static str,
    status_type: HttpsStatusType,
}

const HTTP_STATUSES: [HttpStatus;62] = [
    HttpStatus { code: 100, title: "Continue", explanation: "The HTTP 100 Continue informational status response code indicates that everything so far is OK and that the client should continue with the request or ignore it if it is already finished.\n\nTo have a server check the request's headers, a client must send Expect: 100-continue as a header in its initial request and receive a 100 Continue status code in response before sending the body.\n\n", status_type: HttpsStatusType::INFORMATIONAL },
    HttpStatus { code: 101, title: "Switching Protocols", explanation: "The HTTP 101 Switching Protocols response code indicates a protocol to which the server switches. The protocol is specified in the Upgrade request header received from a client.\n\nThe server includes in this response an Upgrade response header to indicate the protocol it switched to.\n\nThe process is described in the following article: Protocol upgrade mechanism\n\n", status_type: HttpsStatusType::INFORMATIONAL },
    HttpStatus { code: 102, title: "Processing", explanation: "Deprecated:This status code is deprecated. When used, clients may still accept it, but simply ignore them.\n\nThe HTTP 102 Processing informational status response code indicates to client that a full request has been received and the server is working on it.\n\nThis status code is only sent if the server expects the request to take significant time. It tells the client that your request is not dead yet.\n\n", status_type: HttpsStatusType::INFORMATIONAL },
    HttpStatus { code: 103, title: "Early Hints", explanation: "Experimental: This is an experimental technology. Check the Browser compatibility table carefully before using this in production.\n\nThe HTTP 103 Early Hints information response may be sent by a server while it is still preparing a response, with hints about the resources that the server is expecting the final response will link.\n\nThis allows a browser to start preloading resources even before the server has prepared and sent that final response.\n\nThe early hint response is primarily intended for use with the Link header, which indicates the resources to be loaded.\n\nIt may also contain a Content-Security-Policy header that is enforced while processing the early hint.\n\nA server might send multiple 103 responses, for example, following a redirect. Browsers only process the first early hint response, and this response must be discarded if the request results in a cross-origin redirect. Preloaded resources from the early hint are effectively pre-pended to the Document's head element, and then followed by the resources loaded in the final response.\n\n", status_type: HttpsStatusType::INFORMATIONAL },
    HttpStatus { code: 200, title: "OK", explanation: "The HTTP 200 OK success status response code indicates that the request has succeeded. A 200 response is cacheable by default.\n\nThe meaning of a success depends on the HTTP request method:\n\n GET: The resource has been fetched and is transmitted in the message body. HEAD: The representation headers are included in the response without any message body POST: The resource describing the result of the action is transmitted in the message body TRACE: The message body contains the request message as received by the server. \n\nThe successful result of a PUT or a DELETE is often not a 200 OK but a 204 No Content (or a 201 Created when the resource is uploaded for the first time).\n\n", status_type: HttpsStatusType::SUCCESSFUL },
    HttpStatus { code: 201, title: "Created", explanation: "The HTTP 201 Created success status response code indicates that the request has succeeded and has led to the creation of a resource.\n\nThe new resource, or a description and link to the new resource, is effectively created before the response is sent back and the newly created items are returned in the body of the message, located at either the URL of the request, or at the URL in the value of the Location header.\n\nThe common use case of this status code is as the result of a POST request.\n\n", status_type: HttpsStatusType::SUCCESSFUL },
    HttpStatus { code: 202, title: "Accepted", explanation: "The HTTP 202 Accepted response status code indicates that the request has been accepted for processing, but the processing has not been completed; in fact, processing may not have started yet.\n\nThe request might or might not eventually be acted upon, as it might be disallowed when processing actually takes place.\n\n202 is non-committal, meaning that there is no way for the HTTP to later send an asynchronous response indicating the outcome of processing the request. It is intended for cases where another process or server handles the request, or for batch processing.\n\n", status_type: HttpsStatusType::SUCCESSFUL },
    HttpStatus { code: 203, title: "Non-Authoritative Information", explanation: "The HTTP 203 Non-Authoritative Information response status indicates that the request was successful but the enclosed payload has been modified by a transforming proxy from that of the origin server's 200 OK response.\n\nThe 203 response is similar to the value 214, meaning Transformation Applied, of the Warning header code, which has the additional advantage of being applicable to responses with any status code.\n\n", status_type: HttpsStatusType::SUCCESSFUL },
    HttpStatus { code: 204, title: "No Content", explanation: "The HTTP 204 No Content success status response code indicates that a request has succeeded, but that the client doesn't need to navigate away from its current page.\n\nThis might be used, for example, when implementing \"save and continue editing\" functionality for a wiki site. In this case a PUT request would be used to save the page, and the 204 No Content response would be sent to indicate that the editor should not be replaced by some other page.\n\nA 204 response is cacheable by default (an ETag header is included in such a response).\n\n", status_type: HttpsStatusType::SUCCESSFUL },
    HttpStatus { code: 205, title: "Reset Content", explanation: "The HTTP 205 Reset Content response status tells the client to reset the document view (ie. clear the content of a form, reset canvas state or the UI).\n\n", status_type: HttpsStatusType::SUCCESSFUL },
    HttpStatus { code: 206, title: "Partial Content", explanation: "The HTTP 206 Partial Content success status response code indicates that the request has succeeded and the body contains the requested ranges of data, as described in the Range header of the request.\n\nIf there is only one range, the Content-Type of the whole response is set to the type of the document, and a Content-Range is provided.\n\nIf several ranges are sent back, the Content-Type is set to multipart/byteranges and each fragment covers one range, with Content-Range and Content-Type describing it.\n\n", status_type: HttpsStatusType::SUCCESSFUL },
    HttpStatus { code: 207, title: "Multi-Status", explanation: "The HTTP 207 Multi-Status response code indicates that there might be a mixture of responses.\n\nThe response body is a text/xml or application/xml HTTP entity with a multistatus root element. The XML body will list all individual response codes.\n\nNote: The ability to return a collection of resources is part of the WebDAV protocol (it may be received by web applications accessing a WebDAV server).   Browsers accessing web pages will never encounter this status code.\n\n", status_type: HttpsStatusType::SUCCESSFUL },
    HttpStatus { code: 208, title: "Already Reported", explanation: "The HTTP 208 Already Reported response status is used in a 207 Multi-Status response to save space and avoid conflicts. If the same resource is requested several times (for example as part of a collection), with different paths, only the first one is reported with 200. Responses for all other bindings will report with this 208 status code, so no conflicts are created and the response stays shorter.\n\nNote:The ability to bind a resource to several paths is an extension to the WebDAV protocol (it may be received by web applications accessing a WebDAV server). Browsers accessing web pages will never encounter this status code.\n\n", status_type: HttpsStatusType::SUCCESSFUL },
    HttpStatus { code: 226, title: "IM Used", explanation: "The HTTP 226 IM Used response status, in the context of delta encodings, is a status code set by the server to indicate that it is returning a delta to the GET request that it received. IM stands for Instance Manipulations, the term used to describe an algorithm generating a delta.\n\nWith delta encoding a server responds to GET requests with differences (called deltas) relative to a given base document (rather than the current document). The client uses the A-IM: HTTP header to indicate which differencing algorithm to use and the If-None-Match: header to hint the server about the last version it got. The server generates a delta, sending it back in an HTTP response with the 226 status code and containing the IM: (with the name of the algorithm used) and Delta-Base: (with the ETag matching the base document associated to the delta) HTTP headers.\n\nNote: Browsers don't support delta encoding with HTTP. This status code is sent back by custom servers used by specific clients.\n\n", status_type: HttpsStatusType::SUCCESSFUL },
    HttpStatus { code: 300, title: "Multiple Choices", explanation: "The HTTP 300 Multiple Choices redirect status response code indicates that the request has more than one possible response.\n\nThe user-agent or the user should choose one of them.\n\nAs there is no standardized way of choosing one of the responses, this response code is very rarely used.\n\nIf the server has a preferred choice, it should generate a Location header.\n\n", status_type: HttpsStatusType::REDIRECTION },
    HttpStatus { code: 301, title: "Moved Permanently", explanation: "The HTTP 301 Moved Permanently redirect status response code indicates that the requested resource has been definitively moved to the URL given by the Location headers. A browser redirects to the new URL and search engines update their links to the resource.\n\nNote: Although the specification requires the method and the body to remain unchanged when the redirection is performed, not all user-agents meet this requirement. Use the 301 code only as a response for GET or HEAD methods and use the 308 Permanent Redirect for POST methods instead, as the method change is explicitly prohibited with this status.\n\n", status_type: HttpsStatusType::REDIRECTION },
    HttpStatus { code: 302, title: "Found", explanation: "The HTTP 302 Found redirect status response code indicates that the resource requested has been temporarily moved to the URL given by the Location header. A browser redirects to this page but search engines don't update their links to the resource (in 'SEO-speak', it is said that the 'link-juice' is not sent to the new URL).\n\nEven if the specification requires the method (and the body) not to be altered when the redirection is performed, not all user-agents conform here - you can still find this type of bugged software out there. It is therefore recommended to set the 302 code only as a response for GET or HEAD methods and to use 307 Temporary Redirect instead, as the method change is explicitly prohibited in that case.\n\nIn the cases where you want the method used to be changed to GET, use 303 See Other instead. This is useful when you want to give a response to a PUT method that is not the uploaded resource but a confirmation message such as: 'you successfully uploaded XYZ'.\n\n", status_type: HttpsStatusType::REDIRECTION },
    HttpStatus { code: 303, title: "See Other", explanation: "The HTTP 303 See Other redirect status response code indicates that the redirects don't link to the requested resource itself, but to another page (such as a confirmation page, a representation of a real-world object — see HTTP range-14 — or an upload-progress page).\n\nThis response code is often sent back as a result of PUT or POST.\n\nThe method used to display this redirected page is always GET.\n\n", status_type: HttpsStatusType::REDIRECTION },
    HttpStatus { code: 304, title: "Not Modified", explanation: "The HTTP 304 Not Modified client redirection response code indicates that there is no need to retransmit the requested resources. It is an implicit redirection to a cached resource. This happens when the request method is a safe method, such as GET or HEAD, or when the request is conditional and uses an If-None-Match or an If-Modified-Since header.\n\nThe response must not contain a body and must include the headers that would have been sent in an equivalent 200 OK response: Cache-Control, Content-Location, Date, ETag, Expires, and Vary.\n\nNote: Many developer tools' network panels of browsers create extraneous requests leading to 304 responses, so that access to the local cache is visible to developers.\n\n", status_type: HttpsStatusType::REDIRECTION },
    HttpStatus { code: 305, title: "Use Proxy", explanation: "Deprecated: The HTTP 305 Use Proxy status code has been deprecated due to security concerns and many HTTP clients ignore this status code.\n\nHTTP response status code 305 Use Proxy is a deprecated HTTP status code returned by an origin server to indicate that the requested resource can only be accessed through a proxy server.\n\nThe 305 Use Proxy status code is used to inform the client that the requested resource must be obtained through a proxy server and includes that proxy address in the Set-Proxy HTTP header or in the Location HTTP header.\n\n", status_type: HttpsStatusType::REDIRECTION },
    HttpStatus { code: 306, title: "", explanation: "", status_type: HttpsStatusType::REDIRECTION },
    HttpStatus { code: 307, title: "Temporary Redirect", explanation: "HTTP 307 Temporary Redirect redirect status response code indicates that the resource requested has been temporarily moved to the URL given by the Location headers.\n\nThe method and the body of the original request are reused to perform the redirected request. In the cases where you want the method used to be changed to GET, use 303 See Other instead. This is useful when you want to give an answer to a PUT method that is not the uploaded resources, but a confirmation message (like \"You successfully uploaded XYZ\").\n\nThe only difference between 307 and 302 is that 307 guarantees that the method and the body will not be changed when the redirected request is made. With 302, some old clients were incorrectly changing the method to GET: the behavior with non-GET methods and 302 is then unpredictable on the Web, whereas the behavior with 307 is predictable. For GET requests, their behavior is identical.\n\n", status_type: HttpsStatusType::REDIRECTION },
    HttpStatus { code: 308, title: "Permanent Redirect", explanation: "The HTTP 308 Permanent Redirect redirect status response code indicates that the resource requested has been definitively moved to the URL given by the Location headers. A browser redirects to this page and search engines update their links to the resource (in 'SEO-speak', it is said that the 'link-juice' is sent to the new URL).\n\nThe request method and the body will not be altered, whereas 301 may incorrectly sometimes be changed to a GET method.\n\nNote: Some Web applications may use the 308 Permanent Redirect in a non-standard way and for other purposes. For example, Google Drive uses a 308 Resume Incomplete response to indicate to the client when an incomplete upload stalled.\n\n", status_type: HttpsStatusType::REDIRECTION },
    HttpStatus { code: 400, title: "Bad Request", explanation: "The HTTP 400 Bad Request response status code indicates that the server cannot or will not process the request due to something that is perceived to be a client error (for example, malformed request syntax, invalid request message framing, or deceptive request routing).\n\nWarning: The client should not repeat this request without modification.\n\n", status_type: HttpsStatusType::CLIENT_ERROR },
    HttpStatus { code: 401, title: "Unauthorized", explanation: "The HTTP 401 Unauthorized response status code indicates that the client request has not been completed because it lacks valid authentication credentials for the requested resource.\n\nThis status code is sent with an HTTP WWW-Authenticate response header that contains information on how the client can request for the resource again after prompting the user for authentication credentials.\n\nThis status code is similar to the 403 Forbidden status code, except that in situations resulting in this status code, user authentication can allow access to the resource.\n\n", status_type: HttpsStatusType::CLIENT_ERROR },
    HttpStatus { code: 402, title: "Payment Required", explanation: "Experimental: This is an experimental technology. Check the Browser compatibility table carefully before using this in production.\n\nThe HTTP 402 Payment Required is a nonstandard response status code that is reserved for future use. This status code was created to enable digital cash or (micro) payment systems and would indicate that the requested content is not available until the client makes a payment.\n\nSometimes, this status code indicates that the request cannot be processed until the client makes a payment. However, no standard use convention exists and different entities use it in different contexts.\n\n", status_type: HttpsStatusType::CLIENT_ERROR },
    HttpStatus { code: 403, title: "Forbidden", explanation: "The HTTP 403 Forbidden response status code indicates that the server understands the request but refuses to authorize it.\n\nThis status is similar to 401, but for the 403 Forbidden status code, re-authenticating makes no difference. The access is tied to the application logic, such as insufficient rights to a resource.\n\n", status_type: HttpsStatusType::CLIENT_ERROR },
    HttpStatus { code: 404, title: "Not Found", explanation: "The HTTP 404 Not Found response status code indicates that the server cannot find the requested resource. Links that lead to a 404 page are often called broken or dead links and can be subject to link rot.\n\nA 404 status code only indicates that the resource is missing: not whether the absence is temporary or permanent. If a resource is permanently removed, use the 410 Gone status instead.\n\n", status_type: HttpsStatusType::CLIENT_ERROR },
    HttpStatus { code: 405, title: "Method Not Allowed", explanation: "The HTTP 405 Method Not Allowed response status code indicates that the server knows the request method, but the target resource doesn't support this method.\n\nThe server must generate an Allow header field in a 405 status code response. The field must contain a list of methods that the target resource currently supports.\n\n", status_type: HttpsStatusType::CLIENT_ERROR },
    HttpStatus { code: 406, title: "Not Acceptable", explanation: "The HTTP 406 Not Acceptable client error response code indicates that the server cannot produce a response matching the list of acceptable values defined in the request's proactive content negotiation headers, and that the server is unwilling to supply a default representation.\n\nProactive content negotiation headers include:\n\n Accept Accept-Encoding Accept-Language \n\nIn practice, this error is very rarely used. Instead of responding using this error code, which would be cryptic for the end user and difficult to fix, servers ignore the relevant header and serve an actual page to the user. It is assumed that even if the user won't be completely happy, they will prefer this to an error code.\n\nIf a server returns such an error status, the body of the message should contain the list of the available representations of the resources, allowing the user to choose among them.\n\n", status_type: HttpsStatusType::CLIENT_ERROR },
    HttpStatus { code: 407, title: "Proxy Authentication Required", explanation: "The HTTP 407 Proxy Authentication Required client error status response code indicates that the request has not been applied because it lacks valid authentication credentials for a proxy server that is between the browser and the server that can access the requested resource.\n\nThis status is sent with a Proxy-Authenticate header that contains information on how to authorize correctly.\n\n", status_type: HttpsStatusType::CLIENT_ERROR },
    HttpStatus { code: 408, title: "Request Timeout", explanation: "The HTTP 408 Request Timeout response status code means that the server would like to shut down this unused connection. It is sent on an idle connection by some servers, even without any previous request by the client.\n\nA server should send the \"close\" Connection header field in the response, since 408 implies that the server has decided to close the connection rather than continue waiting.\n\nThis response is used much more since some browsers, like Chrome, Firefox 27+, and IE9, use HTTP pre-connection mechanisms to speed up surfing.\n\nNote: some servers merely shut down the connection without sending this message.\n\n", status_type: HttpsStatusType::CLIENT_ERROR },
    HttpStatus { code: 409, title: "Conflict", explanation: "The HTTP 409 Conflict response status code indicates a request conflict with the current state of the target resource.\n\nConflicts are most likely to occur in response to a PUT request. For example, you may get a 409 response when uploading a file that is older than the existing one on the server, resulting in a version control conflict.\n\n", status_type: HttpsStatusType::CLIENT_ERROR },
    HttpStatus { code: 410, title: "Gone", explanation: "The HTTP 410 Gone client error response code indicates that access to the target resource is no longer available at the origin server and that this condition is likely to be permanent.\n\nIf you don't know whether this condition is temporary or permanent, a 404 status code should be used instead.\n\nNote: A 410 response is cacheable by default.\n\n", status_type: HttpsStatusType::CLIENT_ERROR },
    HttpStatus { code: 411, title: "Length Required", explanation: "The HTTP 411 Length Required client error response code indicates that the server refuses to accept the request without a defined Content-Length header.\n\nNote: by specification, when sending data in a series of chunks, the Content-Length header is omitted and at the beginning of each chunk you need to add the length of the current chunk in hexadecimal format. See Transfer-Encoding for more details.\n\n", status_type: HttpsStatusType::CLIENT_ERROR },
    HttpStatus { code: 412, title: "Precondition Failed", explanation: "The HTTP 412 Precondition Failed client error response code indicates that access to the target resource has been denied. This happens with conditional requests on methods other than GET or HEAD when the condition defined by the If-Unmodified-Since or If-None-Match headers is not fulfilled. In that case, the request, usually an upload or a modification of a resource, cannot be made and this error response is sent back.\n\n", status_type: HttpsStatusType::CLIENT_ERROR },
    HttpStatus { code: 413, title: "Payload Too Large", explanation: "The HTTP 413 Content Too Large response status code indicates that the request entity is larger than limits defined by server; the server might close the connection or return a Retry-After header field.\n\nPrior to RFC 9110 the response phrase for the status was Payload Too Large. That name is still widely used.\n\n", status_type: HttpsStatusType::CLIENT_ERROR },
    HttpStatus { code: 414, title: "URI Too Long", explanation: "The HTTP 414 URI Too Long response status code indicates that the URI requested by the client is longer than the server is willing to interpret.\n\nThere are a few rare conditions when this might occur:\n\n when a client has improperly converted a POST request to a GET request with long query information, when the client has descended into a loop of redirection (for example, a redirected URI prefix that points to a suffix of itself), or when the server is under attack by a client attempting to exploit potential security holes. \n\n", status_type: HttpsStatusType::CLIENT_ERROR },
    HttpStatus { code: 415, title: "Unsupported Media Type", explanation: "The HTTP 415 Unsupported Media Type client error response code indicates that the server refuses to accept the request because the payload format is in an unsupported format.\n\nThe format problem might be due to the request's indicated Content-Type or Content-Encoding, or as a result of inspecting the data directly.\n\n", status_type: HttpsStatusType::CLIENT_ERROR },
    HttpStatus { code: 416, title: "Range Not Satisfiable", explanation: "The HTTP 416 Range Not Satisfiable error response code indicates that a server cannot serve the requested ranges. The most likely reason is that the document doesn't contain such ranges, or that the Range header value, though syntactically correct, doesn't make sense.\n\nThe 416 response message contains a Content-Range indicating an unsatisfied range (that is a '*') followed by a '/' and the current length of the resource. E.g. Content-Range: bytes */12777.\n\nFaced with this error, browsers usually either abort the operation (for example, a download will be considered as non-resumable) or ask for the whole document again.\n\n", status_type: HttpsStatusType::CLIENT_ERROR },
    HttpStatus { code: 417, title: "Expectation Failed", explanation: "The HTTP 417 Expectation Failed client error response code indicates that the expectation given in the request's Expect header could not be met.\n\n", status_type: HttpsStatusType::CLIENT_ERROR },
    HttpStatus { code: 418, title: "I'm A Teapot", explanation: "The HTTP 418 I'm a teapot client error response code indicates that the server refuses to brew coffee because it is, permanently, a teapot.\n\nA combined coffee/tea pot that is temporarily out of coffee should instead return 503. This error is a reference to Hyper Text Coffee Pot Control Protocol defined in April Fools' jokes in 1998 and 2014.\n\nSome websites use this response for requests they do not wish to handle, such as automated queries.\n\n", status_type: HttpsStatusType::CLIENT_ERROR },
    HttpStatus { code: 421, title: "Misdirected Request", explanation: "The HTTP 421 Misdirected Request client error response code indicates that the request was directed to a server that is not able to produce a response. This might be possible if a connection is reused or if an alternative service is selected.\n\n", status_type: HttpsStatusType::CLIENT_ERROR },
    HttpStatus { code: 422, title: "Unprocessable Entity", explanation: "The HTTP 422 Unprocessable Content response status code indicates that the server understands the content type of the request entity, and the syntax of the request entity is correct, but it was unable to process the contained instructions.\n\nWarning: The client should not repeat this request without modification.\n\n", status_type: HttpsStatusType::CLIENT_ERROR },
    HttpStatus { code: 423, title: "Locked", explanation: "The HTTP 423 Locked error response code indicates that either the resources tentatively targeted by is locked, meaning it can't be accessed. Its content should contain some information in WebDAV's XML format.\n\nNote: The ability to lock a resource is specific to some WebDAV servers. Browsers accessing web pages will never encounter this status code; in the erroneous cases it happens, they will handle it as a generic 400 status code.\n\n", status_type: HttpsStatusType::CLIENT_ERROR },
    HttpStatus { code: 424, title: "Failed Dependency", explanation: "The HTTP 424 Failed Dependency client error response code indicates that the method could not be performed on the resource because the requested action depended on another action, and that action failed.\n\nRegular web servers will normally not return this status code. But some other protocols, like WebDAV, can return it. For example, in WebDAV, if a PROPPATCH request was issued, and one command fails then automatically every other command will also fail with 424 Failed Dependency.\n\n", status_type: HttpsStatusType::CLIENT_ERROR },
    HttpStatus { code: 426, title: "Upgrade Required", explanation: "The HTTP 426 Upgrade Required client error response code indicates that the server refuses to perform the request using the current protocol but might be willing to do so after the client upgrades to a different protocol.\n\nThe server sends an Upgrade header with this response to indicate the required protocol(s).\n\n", status_type: HttpsStatusType::CLIENT_ERROR },
    HttpStatus { code: 428, title: "Precondition Required", explanation: "The HTTP 428 Precondition Required response status code indicates that the server requires the request to be conditional.\n\nTypically, this means that a required precondition header, such as If-Match, is missing.\n\nWhen a precondition header is not matching the server side state, the response should be 412 Precondition Failed.\n\n", status_type: HttpsStatusType::CLIENT_ERROR },
    HttpStatus { code: 429, title: "Too Many Requests", explanation: "The HTTP 429 Too Many Requests response status code indicates the user has sent too many requests in a given amount of time (\"rate limiting\").\n\nA Retry-After header might be included to this response indicating how long to wait before making a new request.\n\n", status_type: HttpsStatusType::CLIENT_ERROR },
    HttpStatus { code: 431, title: "Requests Headers Fields Too Large", explanation: "The HTTP 431 Request Header Fields Too Large response status code indicates that the server refuses to process the request because the request's HTTP headers are too long. The request may be resubmitted after reducing the size of the request headers.\n\n431 can be used when the total size of request headers is too large, or when a single header field is too large. To help those running into this error, indicate which of the two is the problem in the response body — ideally, also include which headers are too large. This lets users attempt to fix the problem, such as by clearing their cookies.\n\nServers will often produce this status if:\n\n The Referer URL is too long There are too many Cookies sent in the request \n\n", status_type: HttpsStatusType::CLIENT_ERROR },
    HttpStatus { code: 451, title: "Unavailable For Legal Reasons", explanation: "The HTTP 451 Unavailable For Legal Reasons client error response code indicates that the user requested a resource that is not available due to legal reasons, such as a web page for which a legal action has been issued.\n\n", status_type: HttpsStatusType::CLIENT_ERROR },
    HttpStatus { code: 500, title: "Internal Server Error", explanation: "The HTTP 500 Internal Server Error server error response code indicates that the server encountered an unexpected condition that prevented it from fulfilling the request.\n\nThis error response is a generic \"catch-all\" response. Usually, this indicates the server cannot find a better 5xx error code to response. Sometimes, server administrators log error responses like the 500 status code with more details about the request to prevent the error from happening again in the future.\n\n", status_type: HttpsStatusType::SERVER_ERROR },
    HttpStatus { code: 501, title: "Not Implemented", explanation: "The HTTP 501 Not Implemented server error response code means that the server does not support the functionality required to fulfill the request.\n\nThis status can also send a Retry-After header, telling the requester when to check back to see if the functionality is supported by then.\n\n501 is the appropriate response when the server does not recognize the request method and is incapable of supporting it for any resource. The only methods that servers are required to support (and therefore that must not return 501) are GET and HEAD.\n\nIf the server does recognize the method, but intentionally does not support it, the appropriate response is 405 Method Not Allowed.\n\nNote: A 501 error is not something you can fix, but requires a fix by the web server you are trying to access.\n\nNote:A 501 response is cacheable by default; that is, unless caching headers instruct otherwise.\n\n", status_type: HttpsStatusType::SERVER_ERROR },
    HttpStatus { code: 502, title: "Bad Gateway", explanation: "The HTTP 502 Bad Gateway server error response code indicates that the server, while acting as a gateway or proxy, received an invalid response from the upstream server.\n\nNote: A Gateway might refer to different things in networking and a 502 error is usually not something you can fix, but requires a fix by the web server or the proxies you are trying to get access through.\n\n", status_type: HttpsStatusType::SERVER_ERROR },
    HttpStatus { code: 503, title: "Service Unavailable", explanation: "The HTTP 503 Service Unavailable server error response code indicates that the server is not ready to handle the request.\n\nCommon causes are a server that is down for maintenance or that is overloaded. This response should be used for temporary conditions and the Retry-After HTTP header should, if possible, contain the estimated time for the recovery of the service.\n\nCaching-related headers that are sent along with this response should be taken care of, as a 503 status is often a temporary condition and responses shouldn't usually be cached.\n\nNote: together with this response, a user-friendly page explaining the problem should be sent.\n\n", status_type: HttpsStatusType::SERVER_ERROR },
    HttpStatus { code: 504, title: "Gateway Timeout", explanation: "The HTTP 504 Gateway Timeout server error response code indicates that the server, while acting as a gateway or proxy, did not get a response in time from the upstream server that it needed in order to complete the request.\n\nNote: A Gateway might refer to different things in networking and a 504 error is usually not something you can fix, but requires a fix by the web server or the proxies you are trying to get access through.\n\n", status_type: HttpsStatusType::SERVER_ERROR },
    HttpStatus { code: 505, title: "", explanation: "", status_type: HttpsStatusType::SERVER_ERROR },
    HttpStatus { code: 506, title: "Variant Also Negotiates", explanation: "The HTTP 506 Variant Also Negotiates response status code may be given in the context of Transparent Content Negotiation (see RFC 2295). This protocol enables a client to retrieve the best variant of a given resource, where the server supports multiple variants.\n\nThe Variant Also Negotiates status code indicates an internal server configuration error in which the chosen variant is itself configured to engage in content negotiation, so is not a proper negotiation endpoint.\n\n", status_type: HttpsStatusType::SERVER_ERROR },
    HttpStatus { code: 507, title: "Insufficient Storage", explanation: "The HTTP 507 Insufficient Storage response status code may be given in the context of the WebDAV protocol (see RFC 4918).\n\nIt indicates that a method could not be performed because the server cannot store the representation needed to successfully complete the request.\n\n", status_type: HttpsStatusType::SERVER_ERROR },
    HttpStatus { code: 508, title: "Loop Detected", explanation: "The HTTP 508 Loop Detected response status code may be given in the context of the WebDAV protocol.\n\nIt indicates that the server terminated an operation because it encountered an infinite loop while processing a request with \"Depth: infinity\". This status indicates that the entire operation failed.\n\n", status_type: HttpsStatusType::SERVER_ERROR },
    HttpStatus { code: 510, title: "Not Extended", explanation: "The HTTP 510 Not Extended response status code is sent in the context of the HTTP Extension Framework, defined in RFC 2774.\n\nIn that specification a client may send a request that contains an extension declaration, that describes the extension to be used. If the server receives such a request, but any described extensions are not supported for the request, then the server responds with the 510 status code.\n\n", status_type: HttpsStatusType::SERVER_ERROR },
    HttpStatus { code: 511, title: "Network Authentication Required", explanation: "The HTTP 511 Network Authentication Required response status code indicates that the client needs to authenticate to gain network access.\n\nThis status is not generated by origin servers, but by intercepting proxies that control access to the network.\n\nNetwork operators sometimes require some authentication, acceptance of terms, or other user interaction before granting access (for example in an internet café or at an airport). They often identify clients who have not done so using their Media Access Control (MAC) addresses.\n\n", status_type: HttpsStatusType::SERVER_ERROR },
    ];

pub struct StatusCodes {}
impl StatusCodes {
    pub fn is_valid(status: i16) -> bool {
        if INFORMATIONAL.contains(&status) {
            return true;
        } else if SUCCESS.contains(&status) {
            return true;
        } else if REDIRECTION.contains(&status) {
            return true;
        } else if CLIENT_ERROR.contains(&status) {
            return true;
        } else if SERVER_ERROR.contains(&status) {
            return true;
        } else {
            return false;
        }
    }

    pub fn get_description(status: i16) -> String {
        match status {
            100 => "Continue".to_string(),
            101 => "Switching Protocols".to_string(),
            102 => "Processing".to_string(),
            103 => "Early Hints".to_string(),
            200 => "OK".to_string(),
            201 => "Created".to_string(),
            202 => "Accepted".to_string(),
            203 => "Non-Authoritative Information".to_string(),
            204 => "No Content".to_string(),
            205 => "Reset Content".to_string(),
            206 => "Partial Content".to_string(),
            207 => "Multi-Status".to_string(),
            208 => "Already Reported".to_string(),
            226 => "IM Used".to_string(),
            300 => "Multiple Choices".to_string(),
            301 => "Moved Permanently".to_string(),
            302 => "Found".to_string(),
            303 => "See Other".to_string(),
            304 => "Not Modified".to_string(),
            305 => "Use Proxy".to_string(),
            306 => "Switch Proxy".to_string(),
            307 => "Temporary Redirect".to_string(),
            308 => "Permanent Redirect".to_string(),
            400 => "Bad Request".to_string(),
            401 => "Unauthorized".to_string(),
            402 => "Payment Required".to_string(),
            403 => "Forbidden".to_string(),
            404 => "Not Found".to_string(),
            405 => "Method Not Allowed".to_string(),
            406 => "Not Acceptable".to_string(),
            407 => "Proxy Authentication Required".to_string(),
            408 => "Request Timeout".to_string(),
            409 => "Conflict".to_string(),
            410 => "Gone".to_string(),
            411 => "Length Required".to_string(),
            412 => "Precondition Failed".to_string(),
            413 => "Payload Too Large".to_string(),
            414 => "URI Too Long".to_string(),
            415 => "Unsupported Media Type".to_string(),
            416 => "Range Not Satisfiable".to_string(),
            417 => "Expectation Failed".to_string(),
            418 => "I'm A Teapot".to_string(),
            421 => "Misdirected Request".to_string(),
            422 => "Unprocessable Entity".to_string(),
            423 => "Locked".to_string(),
            424 => "Failed Dependency".to_string(),
            425 => "Too Early".to_string(),
            426 => "Upgrade Required".to_string(),
            428 => "Precondition Required".to_string(),
            429 => "Too Many Requests".to_string(),
            431 => "Requests Headers Fields Too Large".to_string(),
            451 => "Unavailable For Legal Reasons".to_string(),
            500 => "Internal Server Error".to_string(),
            501 => "Not Implemented".to_string(),
            502 => "Bad Gateway".to_string(),
            503 => "Service Unavailable".to_string(),
            504 => "Gateway Timeout".to_string(),
            505 => "HTTP Version Not Supported".to_string(),
            506 => "Variant Also Negotiates".to_string(),
            507 => "Insufficient Storage".to_string(),
            508 => "Loop Detected".to_string(),
            510 => "Not Extended".to_string(),
            511 => "Network Authentication Required".to_string(),
            _ => "Unknown".to_string(),
        }
    }

    pub fn get_explanation(_status: i16) -> String {
        HTTP_STATUSES.iter().find(|status| status.code == _status).map_or_else(
            || "Unknown".to_string(),
            |status| status.explanation.to_string()
        )
    }
}
